/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.udistrital.informatica.view;

import com.udistrital.informatica.model.Figure;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;


/**
 * The Class Canvas
 * @author angelicaquevedo
 * 12/09/2020
 */
public class Canvas  extends javax.swing.JPanel {
    
   /**
     * The Figure list
    */
    private List<Figure> shapeList;
    
    /**
     * Creates new form Canvas
     */
    public Canvas() {
        initComponents();
        shapeList = new ArrayList<>();
    }

    @Override
    protected void paintComponent(Graphics g) {
         if (shapeList.isEmpty()){
        }
        super.paintComponent(g);
        for (Figure figure : shapeList) {
            figure.draw(g);
        }
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(450, 450);
    }
    
    /**
     * @return List<Figure>
     */
    public List<Figure> getListaFiguras(){
        return this.shapeList;
    }
    
    /**
     * @param List<Figure>
     */
    public void setListaFiguras(List<Figure> shapeList){
        this.shapeList = shapeList;
    }
    
                 



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(450, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}